[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "weather"
path = "src/main.rs"

[lib]
name = "weather"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toolslib = { path = "../toolslib" }
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
thousands = "0.2.0"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
csv = "1.1"
zip = "0.6.2"
log = "0.4"
