[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
zip = "0.6.2"
thousands = "0.2.0"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
#regex = "1"
#lazy_static = "1.4.0"
csv = "1.1"