[workspace]
resolver = "2"
members = [
    "cli",
    "fslib",
]

[workspace.dependencies]
toolslib = { path = "../toolslib" }
chrono = "0.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
